/****************************************
* server :	Nemoria2
* author :	Varkos
* source :	Client
* version :	1.0
****************************************/

/*** YMIR Locale ***/
#define LOCALE_SERVICE_EUROPE

/*** YMIR System ***/
#define ENABLE_ACCE_COSTUME_SYSTEM
#define ENABLE_COSTUME_SYSTEM
#define ENABLE_DRAGON_SOUL_SYSTEM
#define ENABLE_DICE_SYSTEM
#define ENABLE_ENERGY_SYSTEM
#define ENABLE_GLOVE_SYSTEM
#define ENABLE_MOUNT_COSTUME_SYSTEM
#define ENABLE_MOVE_CHANNEL
#define ENABLE_NEW_EQUIPMENT_SYSTEM
#define ENABLE_PENDANT_SYSTEM
#define ENABLE_QUIVER_SYSTEM
#define ENABLE_WEAPON_COSTUME_SYSTEM

/*** N2 - Features ***/
#define ENABLE_4TH_AFF_SKILL_DESC
#define ENABLE_CANSEEHIDDENTHING_FOR_GM
#define ENABLE_DISCORD_RPC
#define ENABLE_EMOJI_SYSTEM
#define ENABLE_EXTEND_INVEN_SYSTEM
#define ENABLE_HIGHLIGHT_NEW_ITEM
#define ENABLE_LEVEL_IN_TRADE
#define ENABLE_LVL115_ARMOR_EFFECT
#define ENABLE_MOUSEWHEEL_EVENT
#define ENABLE_NO_DSS_QUALIFICATION
#define ENABLE_OBJ_SCALLING
#define ENABLE_PACK_GET_CHECK
#define ENABLE_PET_SYSTEM_EX
#define ENABLE_PLAYER_PER_ACCOUNT5
#define ENABLE_PROTOSTRUCT_AUTODETECT
#define ENABLE_SLOT_WINDOW_EX
#define ENABLE_SLOT_COVER_IMAGE_SYSTEM
#define ENABLE_STEALTH_FIX
#define ENABLE_USE_COSTUME_ATTR
#define ENABLE_SWAP_SLOT_SYSTEM
#define ENABLE_NEW_DROP_DIALOG
#define ENABLE_EMOTION_HIDE_WEAPON

/*** N2 - System ***/
#define ENABLE_SAFEBOX_MONEY
#define ENABLE_PLAYER_PIN_SYSTEM
#define ENABLE_HIDE_COSTUME_SYSTEM

#define ENABLE_VIEW_TARGET_DECIMAL_HP
#ifdef ENABLE_VIEW_TARGET_DECIMAL_HP
	#define ENABLE_VIEW_TARGET_PLAYER_HP
#endif

/*** N2 - Environment ***/
#define REMOVE_SAFEZONE_COLLISION
#define REMOVE_SHOP_COLLISION
#define REMOVE_HORSE_COLLISION
#define REMOVE_PET_COLLISION
#define REMOVE_MOUNTS_COLLISIONS
#define REMOVE_OX_PLAYER_COLLISION
#define REMOVE_KINGDOM_FLAGS

/*** WJ Features ***/
#define WJ_SHOW_MOB_INFO
#ifdef WJ_SHOW_MOB_INFO
	#define ENABLE_SHOW_MOBAIFLAG
	#define ENABLE_SHOW_MOBLEVEL
	#define ENABLE_SHOW_BOSSMARK
	#define ENABLE_SHOW_STONEMARK
#endif